### ISSUE TITLE
Add good CORS default settings (default: allow all / deny all?)

### ISSUE THREAD

**Issue by christoph-kluge** [christoph-kluge/reactphp-http-cors-middleware#1]
Currently I took the default settings from https://enable-cors.org/server_nginx.html which seems a bit unnecessary to me. (i.e. Allow Headers and Expose Headers contain something like: `X-CustomHeader`).. 

At the same page I'm asking myself: 

* Should the default be allow all? (maybe too open for some apps?)
* Should the default deny everything? (so developers are aware of opening the restrictions)

@clue, @jsor, @WyriHaximus any suggestions here? Would appreciate your feedback.

**Comment by jsor** [comment]
> Should the default deny everything? (so developers are aware of opening the restrictions)

That'd be my preference 👍

**Comment by WyriHaximus** [comment]
> > Should the default deny everything? (so developers are aware of opening the restrictions)

> That'd be my preference :+1:

Mine as well, since a dev will be adding this middleware it should also read the documentation IMHO. See it as a firewall you enable which blocks everything by default and you only open up what you want to allow.

**Comment by christoph-kluge** [comment]
Thanks for feedback. I also prefer the "blacklist everything and whitelist specifics" approach. I will tackle this asap!

**Comment by christoph-kluge** [comment]
Closed by #2.
