### ISSUE TITLE
Support: Strict Host-Header checking

### ISSUE THREAD

**Issue by christoph-kluge** [christoph-kluge/reactphp-http-cors-middleware#5]
Currently we're able to accept any incoming `Host` header. 

This means that someone could simply use it's own domain and point it to our application (IP-Adresse/Loadbalancer). This might be a potential security issue. We should definitely add support for this. 

`Neomerx\Cors` has a feature to force strict host-checking and validate the incoming `Host` header. There is an attempt to support this feature already in a [work-in-progress branch](https://github.com/christoph-kluge/reactphp-http-cors-middleware/commit/8bc1f8d9fba023b6997381de7845c8f2ce5fc46f).

**Comment by esokullu** [comment]
So, what's missing, what's preventing this branch to merged into master? Let us know and maybe we can help?

**Comment by christoph-kluge** [comment]
Hi @esokullu, thank you for your support! Out of my mind I guess tests are missing. 

Did a quick check on my local state of the branch and there is nothing lying around here. I will attempt to revalidate my changes tonight (CEST). Hopefully I can recall why I stopped there and created a ticket for it. If it's just the tests then I could simply add them and push the code. If it's more than that I would extend this issue with more useful information.

**Comment by christoph-kluge** [comment]
@esokullu are you up for a review? I would appreciate a second pair of eyes 👍
